create table clients
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login        VARCHAR(50) UNIQUE NOT NULL,
    password     VARCHAR(100)       NOT NULL,
    full_name    VARCHAR(255),
    gender       VARCHAR(255),
    email        VARCHAR(100),
    social_media VARCHAR(15),
    notes        VARCHAR(255),
    primary key (id)
);

CREATE TABLE employees
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login     VARCHAR(50) UNIQUE NOT NULL,
    password  VARCHAR(100)       NOT NULL,
    full_name VARCHAR(255),
    position  VARCHAR(20),
    primary key (id)
);

create table orders
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status     VARCHAR(20) CHECK (status in ('ACTIVE', 'CANCELED', 'COMPLETED')),
    details    VARCHAR(255),
    order_date DATE DEFAULT CURRENT_DATE,
    client_id  BIGINT NOT NULL,
    FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE,
    primary key (id)
);



